name: Release to NPM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node LTS ✨
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org
          cache: pnpm

      - name: Install dependencies 📦️
        run: pnpm install --frozen-lockfile

      - name: Build project 🔨
        run: pnpm build

      - name: Ensure Git tags exist ✅
        run: |
          if [ -z "$(git tag)" ]; then
            echo "No Git tags found. Creating default v1.1.3 tag..."
            git tag v1.1.3
            git push origin v1.1.3
          fi

      - name: Publish to npm 🚀
        uses: simenandre/publish-with-pnpm@v2
        with:
          npm-auth-token: ${{ secrets.NPM_TOKEN }}
